In [2]:
import torch
import numpy as np
import matplotlib

In [6]:
x = torch.rand(5, 3)
print(x)
print(torch.cuda.is_available())
print(torch.has_cuda)

device = torch.device("cuda")
x = torch.ones(5,device = device)
y = torch.ones(5)
y = y.to(device)
z = x+y
z = z.to("cpu")
z = z.numpy()
print(x,y,z)


tensor([[0.1718, 0.2673, 0.4124],
        [0.2123, 0.7507, 0.0582],
        [0.9608, 0.5457, 0.4963],
        [0.3635, 0.0936, 0.9053],
        [0.9507, 0.5458, 0.9349]])
True
True
tensor([1., 1., 1., 1., 1.], device='cuda:0') tensor([1., 1., 1., 1., 1.], device='cuda:0') [2. 2. 2. 2. 2.]


In [8]:
x = torch.randn(3, requires_grad=True)
print(x)
y= x+2
print(y)
y.backward() #dy/dx

tensor([ 0.3724,  0.2993, -0.1509], requires_grad=True)
tensor([2.3724, 2.2993, 1.8491], grad_fn=<AddBackward0>)
