In [2]:
import torch
import numpy as np
import matplotlib

In [3]:
x = torch.rand(5, 3)
print(x)
print(torch.cuda.is_available())
print(torch.has_cuda)

device = torch.device("cuda")
x = torch.ones(5,device = device)
y = torch.ones(5)
y = y.to(device)
z = x+y
z = z.to("cpu")
z = z.numpy()
print(x,y,z)


tensor([[0.7435, 0.0333, 0.3102],
        [0.2517, 0.9279, 0.1265],
        [0.0305, 0.7079, 0.2743],
        [0.9130, 0.1177, 0.1049],
        [0.6337, 0.5597, 0.4999]])
True
True
tensor([1., 1., 1., 1., 1.], device='cuda:0') tensor([1., 1., 1., 1., 1.], device='cuda:0') [2. 2. 2. 2. 2.]


In [8]:
x = torch.randn(3, requires_grad=True)
print(x)
y= x+2
print(y)
y.backward() #dy/dx

tensor([ 0.3724,  0.2993, -0.1509], requires_grad=True)
tensor([2.3724, 2.2993, 1.8491], grad_fn=<AddBackward0>)
